version: "3"

services:
  ci-test:
    image: sifishome/ci-test-app:latest
    ports:
      - 5050:5050/tcp

  watchtower:
    image: containrrr/watchtower
    command: --interval 30
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
